Math magicians: components 🧭
ismailmunyentwari9/Math-magicians pull request #2
Opened 2023-03-21 21:36 UTC by ismailmunyentwari9

# What I have done in this project part 👍🏼 

- [ ] Implement the design only (JSX and CSS)
- [ ] Develop just the UI of the calculator.
- [ ] Use functional components
- [ ] Create at least 1 child component
- [ ] Test it in the browser; it should render without problems.
# 🧠Skills Obtained in this project implementation 🌹 

- Use React `components`.

2023-03-21 21:44 UTC, julie-ify commented
Hi @ismailmunyentwari9,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project that does not have a descriptive readme file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-21 22:11 UTC, mikethreels requested changes
Hi Isma, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- linters are passing

## Required Changes ♻️
- [ ] there is still some boilerplate that got created by the CRA which should be deleted, in the public folder only the index.html file has to stay and in the src folder the test files, styles and the Webvitals file can be removed as well.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 22:11 UTC, mikethreels commented on src/App.css
> +  background-color: hsl(0, 0%, 100%);
- [ ] please make sure to match the design requirements set by Microverse as close as possible.
your project:
![afbeelding](https://user-images.githubusercontent.com/39240820/226752765-d3badc76-603b-404c-a2c3-f2abf33665c9.png)
Requested design:
![afbeelding](https://user-images.githubusercontent.com/39240820/226752830-b96d3f81-1a96-452c-9bbc-d28761e1aae1.png)

2023-03-22 08:47 UTC, pinkmoon25 requested changes
Hi @ismailmunyentwari9 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
Linter checks :heavy_check_mark: 
Gitflow :heavy_check_mark: 
Calculator Design :heavy_check_mark: 

 ## Required Changes ♻️

**- [ ] As requested by the previous reviewer please make sure to delete all the boilerplate generated by CRA, such as logo images from public folder, app.test.js and setupTest.js as they are redundant** :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 09:09 UTC, OyePriscilla approved these changes
Hi @ismailmunyentwari9 👏 👏 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
App worked as expected 👍 
Used React Components ✔️ 
Remove boilerplate that got created by the CRA 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-22 09:40 UTC, merged